### ISSUE TITLE
เปิดไฟล์ไม่ได้ครับ

### ISSUE THREAD

**Issue by chukiatt** [omise/banks-logo#2]
download มาแล้ว เปิดไฟล์ svg ใน browser ไม่ได้น่ะครับ ไม่ทราบว่าผมทำอะไรผิดหรือเปล่าครับ ลองกับไฟล์อื่นเปิดได้น่ะครับ

ขอบคุณมากครับ

**Comment by danfowler** [comment]
เนื่องจากไฟล์ svg มีสีขาวจึงไม่แสดงบนฉากหลังที่มีสีขาวเหมือนกัน

👀 https://github.com/omise/banks-logo/blob/master/th/baac.svg 
🙈 https://raw.githubusercontent.com/omise/banks-logo/master/th/baac.svg

**Comment by chukiatt** [comment]
ขอบคุณมากครับ
